version: '2'
services:
  kafka:
    image: landoop/fast-data-dev
    ports:
      - "2181:2181"
      - "3030:3030"
      - "3031:3031"
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    environment:
      ADV_HOST: kafka
  magic:
    image: digitsy/kafka-magic
    ports:
      - "9099:80"
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"

# Just run docker-compose up and navigate to http://localhost:9099